[project]
authors = [{name = "Hugo Merzisen", email = "hugo.merzisen@meteo.fr"}]
dependencies = []
name = "dempy"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
dempy = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
matplotlib = ">=3.11.1,<4"
pandas = ">=3.0.5,<4"
numba = ">=0.67.0,<0.68"
numpy = ">=2.5.2,<3"
pooch = ">=1.9.0,<2"
xarray = ">=2026.7.0,<2027"
rioxarray = ">=0.23.0,<0.24"
dask = ">=2026.8.0,<2027"
pyfftw = ">=0.15.1,<0.16"
scipy = ">=1.18.0,<2"
zarr = ">=3.3.0,<4"
opencv = ">=5.0.0,<6"
